import express from "express";
import nodemailer from "nodemailer";
import multer from "multer";
import cors from "cors";
import dotenv from "dotenv";
import path from "path";

dotenv.config();

const app = express();
const upload = multer({ storage: multer.memoryStorage() });

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.post("/api/send-email", upload.array("file"), async (req, res) => {
  const { name, email, country, message, category, Portfolio } = req.body;

  const senderEmail = category === "I am a Creator"
    ? process.env.TALENT_EMAIL
    : process.env.BRAND_EMAIL;

  const senderPass = category === "I am a Creator"
 ? process.env.TALENT_PASS
    : process.env.BRAND_PASS;

  const transporter = nodemailer.createTransport({
    host: "smtp.zoho.com",
    port: 465,
    secure: true,
    auth: {
      user: senderEmail,
      pass: senderPass,
    },
  });

  try {
    const attachments = (req.files || []).map((file) => ({
      filename: file.originalname,
      content: file.buffer,
    }));

    await transporter.sendMail({
      from: `Website Form <${senderEmail}>`,
      to: senderEmail,
      replyTo: email,
      subject: `New message from ${name}`,
      text:
        `Category: ${category}
From: ${name}
Email: ${email}
${country ? `Country: ${country}` : ""}
${Portfolio ? `Portfolio Link: ${Portfolio}` : ""}

${message}`,
      attachments,
    });

    res.status(200).json({ success: true });
  } catch (error) {
    console.error("Email send error:", error);
    res.status(500).json({ success: false, error: error.message });
  }
});

// newsletter endpoint that sends an email to the brand inbox
app.post("/api/newsletter", async (req, res) => {
  try {
    const { name, email } = req.body;

    if (!email) {
      return res.status(400).json({ success: false, message: "Email is required" });
    }

    const senderEmail = process.env.BRAND_EMAIL;
    const senderPass  = process.env.BRAND_PASS;

    if (!senderEmail || !senderPass) {
      return res.status(500).json({
        success: false,
        message: "Mail sender credentials are not configured on the server.",
      });
    }

    // create transporter for Zoho SMTP
    const transporter = nodemailer.createTransport({
      host: "smtp.zoho.com", // use your provider's SMTP if not Zoho
      port: 465,
      secure: true,
      auth: {
        user: senderEmail,
        pass: senderPass,
      },
    });

    const mailOptions = {
      from: `Website Newsletter <${senderEmail}>`,
      to: senderEmail, // brand inbox receives the subscription
      subject: `New newsletter signup: ${name || "No name provided"}`,
      text: `A new newsletter signup was received.\n\nName: ${name || "(not provided)"}\nEmail: ${email}\n\n--\nThis message was generated by the website.`,
      html: `<p>A new newsletter signup was received.</p>
             <ul>
               <li><strong>Name:</strong> ${name || "(not provided)"}</li>
               <li><strong>Email:</strong> ${email}</li>
             </ul>`,
    };

    await transporter.sendMail(mailOptions);

    return res.json({ success: true, message: "Subscription received and email sent." });
  } catch (err) {
    console.error("Newsletter sending error:", err);
    return res.status(500).json({ success: false, message: "Failed to send notification email.", error: err.message });
  }
});


// Allow CORS for your frontend (local or deployed)
app.use(cors({
  origin: "http://localhost:3000", // or your deployed frontend URL
  methods: "POST",
}));

// ✅ Start the server and log the port
const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`🚀 Server is running on http://localhost:${PORT}`);
});
