import { Resend } from "resend";

export async function onRequestPost({ request, env }) {
  try {
    const { name, email } = await request.json();

    if (!email) {
      return new Response(
        JSON.stringify({ success: false, message: "Email is required" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    const senderEmail = env.BRAND_EMAIL;
    const resend = new Resend(env.RESEND_API_KEY);

    const subject = `New newsletter signup: ${name || "No name provided"}`;
    const text = `A new newsletter signup was received.\n\nName: ${name || "(not provided)"}\nEmail: ${email}\n\n--\nThis message was generated by the website.`;

    const response = await resend.emails.send({
      from: `Website Newsletter <${senderEmail}>`,
      to: [senderEmail],
      subject,
      text,
    });

    return new Response(
      JSON.stringify({ success: true, message: "Subscription received.", response }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Newsletter send error:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
